# Site settings
title: AP Bioinformatics - Data Science, Statistics & Programming
email: alexvpickering@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Exploratory omics for a longer and healthier life.
baseurl:  # the subpath of your site, e.g. /blog/
url:  "http://alexvpickering.com"
twitter_username: alexvpickering
github_username:  alexvpickering
logo: "http://alexvpickering.com/img/logo.png"

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]


#collections:
#  portfolio:
#    output: true
#    permalink: /portfolio/:path/
#  poetry:
#    output: true
#    permalink: /poetry/:path/

exclude: [extrastuff/]

disqus:
    shortname: 'alexvpickering'

# Open Graph
fb_admins: https://www.facebook.com/alexvpickering
fb_appid: 100002228785974
